# Generated by Django 2.0.8 on 2018-10-27 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juntagrico', '0015_auto_20180924_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitations', models.CharField(max_length=200, verbose_name='Einladungen')),
                ('anonymous', models.BooleanField(verbose_name='Keine Namensnennung')),
                ('date_ordered', models.DateField(verbose_name='Bestellt am')),
                ('date_paid', models.DateField(verbose_name='Bezahlt am')),
            ],
        ),
        migrations.CreateModel(
            name='Fundable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('quantity', models.PositiveIntegerField(verbose_name='Gesamtzahl')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preis')),
            ],
        ),
        migrations.AddField(
            model_name='fund',
            name='fundable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juntagrico_crowdfunding.Fundable'),
        ),
        migrations.AddField(
            model_name='fund',
            name='member',
            field=models.ManyToManyField(to='juntagrico.Member'),
        ),
    ]
