# Generated by Django 2.0.8 on 2018-10-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_crowdfunding', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'verbose_name': 'Unterstützung', 'verbose_name_plural': 'Unterstützungen'},
        ),
        migrations.AlterModelOptions(
            name='fundable',
            options={'verbose_name': 'Unterstützungsart', 'verbose_name_plural': 'Unterstützungsarten'},
        ),
        migrations.AlterField(
            model_name='fund',
            name='date_paid',
            field=models.DateField(blank=True, verbose_name='Bezahlt am'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='invitations',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Einladungen'),
        ),
    ]
