# Generated by Django 2.0.8 on 2018-10-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_crowdfunding', '0002_auto_20181027_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='date_paid',
            field=models.DateField(blank=True, null=True, verbose_name='Bezahlt am'),
        ),
    ]
