# Generated by Django 2.0.8 on 2018-10-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_crowdfunding', '0003_auto_20181027_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='contribution',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=9, verbose_name='Beitrag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fund',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Mitteilung'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='date_ordered',
            field=models.DateField(auto_now_add=True, verbose_name='Bestellt am'),
        ),
        migrations.AlterField(
            model_name='fundable',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preis/Einheit'),
        ),
    ]
