# Generated by Django 2.0.8 on 2018-11-08 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_crowdfunding', '0004_auto_20181027_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Bild-URL')),
                ('active', models.BooleanField(verbose_name='Aktiv')),
                ('vocabulary_fundable', models.CharField(default='Patenschaft', max_length=200, verbose_name='Bezeichnung: Unterstützungsart')),
                ('vocabulary_fundables', models.CharField(default='Patenschaften', max_length=200, verbose_name='Bezeichnung: Unterstützungsarten')),
                ('vocabulary_whoIsSponsor', models.TextField(default='Auf wen soll die Patenschaft lauten (Vorname(n))?', verbose_name='Formular: Patenschaftsnennung')),
                ('vocabulary_confirmOrder', models.TextField(default='Bei Bestätigung kaufe ich eine Patenschaft und mache damit eine Schenkung an die Genossenschaft MehalsGmües. Ich kriege eine Patenschaftsbestätigung (Karte - als Geschenk geeignet) per Post. Der Name, auf welchen die Patenschaft lautet, wird auf einer Tafel in der Gärtnerei verewigt.', verbose_name='Formular: Kauf bestätigen')),
                ('vocabulary_confirmOrderButton', models.CharField(default='Verbindlich bestätigen', max_length=200, verbose_name='Formular: Button Verbindlich bestätigen')),
                ('vocabulary_thankYouTitle', models.CharField(default='Vielen Dank', max_length=200, verbose_name='Titel: Dankeschön')),
                ('vocabulary_thankYouMessage', models.TextField(default='ladida', verbose_name='Text: Dankeschön')),
            ],
            options={
                'verbose_name': 'Unterstützungs-Projekt',
                'verbose_name_plural': 'Unterstützungs-Projekte',
            },
        ),
        migrations.RemoveField(
            model_name='fund',
            name='invitations',
        ),
        migrations.AddField(
            model_name='fund',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Kommentar'),
        ),
        migrations.AddField(
            model_name='fund',
            name='sponsor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pate(n)'),
        ),
        migrations.AddField(
            model_name='fundable',
            name='funding_project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='juntagrico_crowdfunding.FundingProject'),
            preserve_default=False,
        ),
    ]
