# Generated by Django 2.0.8 on 2018-11-14 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('juntagrico_crowdfunding', '0005_auto_20181108_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nachname')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('addr_street', models.CharField(max_length=100, verbose_name='Strasse')),
                ('addr_zipcode', models.CharField(max_length=10, verbose_name='PLZ')),
                ('addr_location', models.CharField(max_length=50, verbose_name='Ort')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefonnr')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UnterstützerIn',
                'verbose_name_plural': 'UnterstützerInnen',
            },
        ),
    ]
