# Generated by Django 2.0.8 on 2018-11-14 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_crowdfunding', '0006_funder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='member',
        ),
        migrations.AddField(
            model_name='fund',
            name='funder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='juntagrico_crowdfunding.Funder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funder',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='funder', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
