# Generated by Django 2.0.8 on 2018-11-18 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_crowdfunding', '0007_auto_20181114_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='anonymous',
        ),
    ]
